; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/matthewburns/github/florish-online/src/clj/flourish-common/src-clj/flourish_common/crossover/macros.clj


(ns flourish-common.crossover.macros)


(defmacro go-loop [& body]
  `(cljs.core.async.macros/go
     (while true
       ~@body)))