#!/bin/sh
export PRJ_ROOT_DIR=$HOME/LandingSite-Delivery
export PERL5LIB=$PRJ_ROOT_DIR/lib:$PERL5LIB
source $HOME/perl5/perlbrew/etc/bashrc
cd $PRJ_ROOT_DIR
$HOME/perl5/perlbrew/perls/perl-5.16.2/bin/plackup --port 3000 --host 127.0.0.1  -a landingsite_delivery.psgi --access-log  ./log/landing_site_access.log
